version: "3"

volumes:
  media:
  db_postgres_data:
  production_traefik:

services:
  db:
    container_name: db_postgres
    image: postgres:13.0-alpine
    volumes:
      - db_postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    env_file:
      - ./tfg/.env

  django:
    container_name: backend_django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend_django
    volumes:
      - media:/home/app/backend/data:Z
    depends_on:
      - db
    expose:
      - 80

  frontend:
    container_name: frontend
    restart: always
    build:  
      context: ./tfg_front
      dockerfile: Dockerfile
    image: vue_frontend
    depends_on:
      - django
    expose:
      - 80
  
  traefik:
    container_name: traefik
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: traefik_front
    depends_on:
      - django
      - frontend
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
