# Generated by Django 4.1.4 on 2023-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_alter_categorymodel_files_alter_categorymodel_packs"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="purchased_packs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Paquetes de muestras/imágenes obtenidos por el usuario",
                related_name="profiles",
                to="categories.pointpackmodel",
            ),
        ),
    ]
