# Generated by Django 4.1.4 on 2023-06-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_purchased_packs"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="group",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Grupo"
            ),
        ),
    ]
