# Generated by Django 4.1.4 on 2022-12-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la actividad', max_length=256, verbose_name='Título')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Theory'), (2, 'Quiz')], default=1, help_text='Tipo de actividad', verbose_name='Tipo')),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, help_text='Categoría de la actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='categories.categorymodel', verbose_name='Categoría')),
            ],
        ),
    ]
