# Generated by Django 4.1.4 on 2023-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionmodel",
            name="correct_option",
            field=models.CharField(
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                ],
                default="A",
                max_length=256,
                verbose_name="Opción correcta",
            ),
        ),
    ]
