# Generated by Django 4.1.4 on 2022-12-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la categoría', max_length=256, verbose_name='Título')),
                ('content', models.TextField(blank=True, help_text='Contenido teórico básico', max_length=32768, null=True, verbose_name='Contenido teórico')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
