# Generated by Django 4.1.4 on 2023-06-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="P_IMG", max_length=256, verbose_name="Nombre"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código para identificar rápidamente paquetes/imágenes",
                        max_length=256,
                        null=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="data/categories/pack_images/", verbose_name="Imagen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack image",
                "verbose_name_plural": "Pack images",
            },
        ),
        migrations.CreateModel(
            name="DocumentFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del documento/archivo",
                        max_length=256,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="data/categories/documents/", verbose_name="Archivo"
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
        migrations.CreateModel(
            name="PointPackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del paquete de muestras",
                        max_length=256,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código para identificar rápidamente paquetes/imágenes",
                        max_length=256,
                        null=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        default=5,
                        help_text="Precio del paquete (en puntos)",
                        verbose_name="Precio",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Muestras/Imágenes disponibles dentro del pack",
                        related_name="pointpacks",
                        to="categories.customimagemodel",
                        verbose_name="Muestras",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point Pack",
                "verbose_name_plural": "Point packs",
            },
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título de la categoría",
                        max_length=256,
                        verbose_name="Título",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Pequeña descripción de la categoría",
                        max_length=1024,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Contenido 'teórico' incluido en la página de la categoría",
                        max_length=32768,
                        null=True,
                        verbose_name="Contenido teórico",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="data/categories/display_images/",
                        verbose_name="Imagen",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "generic",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se utilizará para para quizzes/elementos sin categoría específica",
                        verbose_name="General",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Archivos adicionales asignados a esta categoría",
                        related_name="categories_file",
                        to="categories.documentfilemodel",
                    ),
                ),
                (
                    "packs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Paquetes de muestras/imágenes asociados a esta categoría",
                        related_name="categories_pack",
                        to="categories.pointpackmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
