# Generated by Django 4.1.4 on 2023-05-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="documents",
                to="categories.documentfilemodel",
            ),
        ),
    ]
