# Generated by Django 4.1.4 on 2023-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categorymodel_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="categories.documentfilemodel"
            ),
        ),
    ]
