# Generated by Django 4.1.4 on 2023-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_categorymodel_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="P_IMG", max_length=256, verbose_name="Nombre"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código para identificar rápidamente paquetes/imágenes",
                        max_length=256,
                        null=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="data/categories/pack_images/", verbose_name="Imagen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack image",
                "verbose_name_plural": "Pack images",
            },
        ),
        migrations.CreateModel(
            name="PointPackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del paquete de muestras",
                        max_length=256,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código para identificar rápidamente paquetes/imágenes",
                        max_length=256,
                        null=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        default=5, help_text="Precio del paquete", verbose_name="Precio"
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Muestras/Imágenes disponibles dentro del pack",
                        related_name="pointpacks",
                        to="categories.customimagemodel",
                        verbose_name="Muestras",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point Pack",
                "verbose_name_plural": "Point packs",
            },
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="packs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Paquetes de muestras/imágenes asociados a esta categoría",
                related_name="packs",
                to="categories.pointpackmodel",
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Archivos adicionales asignados a esta categoría",
                related_name="documents",
                to="categories.documentfilemodel",
            ),
        ),
    ]
