# Generated by Django 4.1.4 on 2023-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_customimagemodel_alter_categorymodel_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointpackmodel",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="pointpackmodel",
            name="price",
            field=models.IntegerField(
                default=5,
                help_text="Precio del paquete (en puntos)",
                verbose_name="Precio",
            ),
        ),
    ]
