# Generated by Django 4.1.4 on 2023-05-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0005_pointpackmodel_active_alter_pointpackmodel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Archivos adicionales asignados a esta categoría",
                related_name="categories_file",
                to="categories.documentfilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="packs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Paquetes de muestras/imágenes asociados a esta categoría",
                related_name="categories_pack",
                to="categories.pointpackmodel",
            ),
        ),
    ]
