# Generated by Django 4.1.4 on 2023-06-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_alter_categorymodel_files_alter_categorymodel_packs"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Orden"),
        ),
    ]
